---
title: "Code book for Access mdb files"
author: "kang"
date: "3/3/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir =  "C:/Users/kangj/Documents/R/KES")
```

Names of all the columns of each table in the Access files. 

```{r, echo=FALSE}
# get names of all the tables in the Access databases
library(RODBC)
func_get_name <- function(name_mdb){
  fvar_driver <- "Driver={Microsoft Access Driver (*.mdb, *.accdb)};"
  fvar_path <- "DBQ=C:/Users/kangj/Documents/R/KES/Tree/"
  my_channel <- odbcDriverConnect(paste0(fvar_driver, fvar_path, name_mdb))
  for (fvar_table in sqlTables(my_channel, tableType = "TABLE")$TABLE_NAME) {
    cat(fvar_table, "\n")
    for (fvar_colname in sqlColumns(my_channel, sqtable = fvar_table)$COLUMN_NAME) {
      cat('"', fvar_colname, '"\n', sep = "")
    }
    cat("\n")
  }
  close(my_channel)
}
list <- for (var_mdb in grep("mdb", list.files("Tree"), value = TRUE)) {
  cat("_____________________\n")
  cat(var_mdb, "\n")
  func_get_name(var_mdb)
}

```


